language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
install: "pip install -U pytest"
install: "pip install -U cv2"
install: "pip install -U scipy"
install: "pip install -U skimage"
install: "pip install -U matplotlib"
install: "pip install -U pandas"

cache: pip
# command to run tests
script:
  - test.py --cov-report term-missing --cov app -v